# Generated by Django 6.0 on 2026-01-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='life_manager.optioncategory'),
        ),
    ]
