# Generated by Django 6.0 on 2026-01-09 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_manager', '0005_chatsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('chat_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_plan_linked', to='life_manager.chatsession')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='life_manager.personalgoal')),
            ],
        ),
        migrations.CreateModel(
            name='GoalTaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('chat_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_task_info_linked', to='life_manager.chatsession')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_info', to='life_manager.personalgoal')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_task_linked', to='life_manager.chatsession')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='life_manager.personalgoal')),
            ],
        ),
    ]
